FROM ava-cuda-10.1

RUN python3 -m pip install torch

RUN mkdir -p /opt/pytorch && cd /opt/pytorch/ && \
    git clone https://github.com/pytorch/examples.git && \
    cd examples && git checkout cbb760d5e50a03df667cdc32a61f75ac28e11cbf
RUN cd /opt/pytorch && \
    git clone -- https://github.com/NVIDIA/DeepLearningExamples.git && \
    cd DeepLearningExamples && git checkout 437b950d5be2cc5d8044378ebf02976d5a21fc13 && \
    cd .. && ln -s ../DeepLearningExamples/PyTorch/Detection/SSD examples/ssd
CMD ["bash"]
