FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
#install ava deps
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
    && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
    && apt-get update \
    && apt-get purge --auto-remove cmake
# install other ava dependencies from "install_dependencies.sh" script
RUN apt-get install -y cmake git build-essential python3 python3-pip libglib2.0-dev \
        clang-7 libclang-7-dev libboost-all-dev libconfig++-dev indent \
        gosu ccache clang-tidy-7 clang-format-7
RUN python3 -m pip install setuptools pkgconfig
RUN python3 -m pip install wget \
        toposort astor 'numpy==1.15.0' blessings

RUN find /root -type f -print0 | xargs -0 chmod 666 \
      && find /root -type d -print0 | xargs -0 chmod 777
RUN echo "export PS1='\\W$ '" >> /root/.bashrc
ENV HOME=/root
# Yes, allow anyone to run as root with gosu
RUN chmod gu+s `which gosu`
VOLUME /root/.ccache
VOLUME /source
WORKDIR /source

CMD ["bash"]
